<a href="https://colab.research.google.com/github/Void-Brain70/Deep_Learning/blob/main/Loss_or_Cost_Function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Mean Absloute Error

In [3]:
import numpy as np

In [2]:
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

In [9]:
def MAE(y_true,y_predicted):
  total_error = 0
  for i,j in zip(y_true,y_predicted):
    total_error += abs(i-j)
  print("Total Error: ",total_error)
  r = total_error / len(y_true)
  print("Mean Absolute Error: ",r)
  return r  

In [10]:
MAE(y_true,y_predicted)

Total Error:  2.5
Mean Absolute Error:  0.5


0.5

In [11]:
np.abs(y_predicted,y_true)

array([1., 1., 0., 0., 1.])

In [12]:
np.mean(np.abs(y_predicted,y_true))

0.6

In [13]:
np.sum(np.abs(y_predicted,y_true))

3.0

Binary Cross Entropy

In [14]:
np.log([0])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([-inf])

In [16]:
epsilon = 1e-15
np.log([1e-15])

array([-34.53877639])

In [17]:
y_predicted

array([1, 1, 0, 0, 1])

In [18]:
y_predicted_new = [max(i,epsilon) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [19]:
1-epsilon
y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [20]:
y_predicted_new = np.array(y_predicted_new)
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [21]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

9.992007221626415e-16

In [23]:
def BCE(y_true, y_predicted):
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [24]:
BCE(y_true,y_predicted)

9.992007221626415e-16